+ address 'PTHREAD_MUTEX_RECURSIVE' undeclared error
  - during compilation i was observing errors such as:

      error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function)

  - added the `-pthread -D_GNU_SOURCE` CFLAGS option to the necessary
    library and binaries being built

    based off of reading the following links:

     https://lists.debian.org/debian-bsd/2011/11/msg00081.html
     https://github.com/idris-lang/Idris-dev/issues/1059
     https://github.com/samtools/bcftools/issues/610
     https://sourceforge.net/p/samtools/mailman/message/35829272/
     https://stackoverflow.com/questions/18375527/why-is-gnu-source-macro-required-for-pthread-mutexattr-settype-while-it-is-in